### ISSUE TITLE
Switch to unite.vim

### ISSUE THREAD

**Issue by marcusandre** [marcusandre/dotfiles#10]
https://github.com/Shougo/unite.vim

I could drop NERDtree as well as CTRL-P…

**Comment by marcusandre** [comment]
ok

**Comment by yoshuawuyts** [comment]
How are you finding `unite` so far? I don't use NerdTree, and am quite fond of Ctrl-P.

**Comment by marcusandre** [comment]
Hi Yoshua, thanks for the request. I dropped NerdTree completely, since I don't have any use-case anymore. I only need a fast fuzzy finder implementation. Ctrl-P ist slow, as long as you don't use `ag` support. I don't have ag on all machines (remote, etc). Unite is very fast, but it can even populate the file tree in an async manner. If you want to try it, please consider to install [vimproc](https://github.com/Shougo/vimproc.vim) ([commit](https://github.com/marcusandre/dotfiles/commit/56d031be87afbbe8ceeeeabe66e93d660f1eeb91))

It's really different to use imho; and even in these few days, it transformed my workflow slightly to the better I think. I even dropped the `-start-insert` flag ([commit](https://github.com/marcusandre/dotfiles/commit/38b1e03ebb436099623f02a01797caa8304e1f20)), which mimics Ctrl-P auto typing behaviour. Therefore I can close the Unite view directly with `q`, which is very fast.

I'm just at the beginning, but why don't we just try it for one or two weeks and compare our opinions right after. :)

**Comment by marcusandre** [comment]
@yoshuawuyts I have to admit: I use fuzzy file finders not to much in the last couple of weeks. `:e` does a great job. :)

**Comment by yoshuawuyts** [comment]
ooh, nice! Still haven't come around to test it out, but definitely intrigued by what you're doing (':
