### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by marcusandre** [marcusandre/dotfiles#11]
- neosnippet for snippets
- add some js snippets

**Comment by yoshuawuyts** [comment]
I've only ever gotten so far to have neosnippet not throw errors, never down to actual snippetteering. What are you using for autocomplete? From my understanding neovim + neosnippet apparently only works well with neocomplcache, which is relatively outdated.

**Comment by marcusandre** [comment]
Oh wow, thanks for your advice Yoshua. I will keep that in mind! Yes, neocomplcache won't quite cut it imho. I don't use any snippets right now; which makes me sad, because I shed so much speed. Since you are not ready yet either, which module/plugin would you suggest to use? I would be happy if I would only have some TAP snippets. I thought about writing an `tape` vim plugin, but that would take years I think. :stuck_out_tongue:

**Comment by yoshuawuyts** [comment]
Snippets in general would be great, for a multitude of languages tbh. This is the code I got so `neocompl{ete,cache}` doesn't break - https://github.com/yoshuawuyts/dotfiles/blob/master/vim/vimrc.symlink#L209-L224 perhaps it's useful? :')

Oh, and before I forget: there's also `deoplete`, which is aimed at nvim but not stable yet. I tried it quickly but couldn't get it working; it should fully integrate with neosnippets though - https://github.com/Shougo/deoplete.nvim

**Comment by marcusandre** [comment]
> Snippets in general would be great, for a multitude of languages tbh. 

Yes. I'm right there with you. It happens quicker than you think, that a project contains many different files. Thinking of `Makefiles` for abstraction, `JSON`, `JavaScript`, `Bash` for scripting and automation. There must be an easy way to use Snippets and their auto-completion across these different files and languages. This is an argument against my `tape`-plugin idea, since it could only fit one single use-case. I think a goal would be to provide a simple yet effective language and abstraction to create snippets right away.

> This is the code I got so neocompl{ete,cache} doesn't break - https://github.com/yoshuawuyts/dotfiles/blob/master/vim/vimrc.symlink#L209-L224 perhaps it's useful? :')

Thank you very much. I will plunge right in as soon as possible. :+1:

**Comment by marcusandre** [comment]
> Oh, and before I forget: there's also deoplete, which is aimed at nvim but not stable yet. I tried it quickly but couldn't get it working; it should fully integrate with neosnippets though - https://github.com/Shougo/deoplete.nvim

I'm curious: have switched completely to __neovim__ yet? I had some indentation issues lately.

**Comment by yoshuawuyts** [comment]
Yeah, I've been using nvim ever since I switched to vim (~8 months ago); it was too slow for me when used on tmux. I haven't had any indentation issues; perhaps if you have any you might want to check your utf8 settings are set correctly?

**Comment by marcusandre** [comment]
> perhaps if you have any you might want to check your utf8 settings are set correctly?

I installed the latest `nvim` via homebrew this time and everything seems to work fine. Thanks!

**Comment by marcusandre** [comment]
@yoshuawuyts still an unsolved problem, right? :(

**Comment by yoshuawuyts** [comment]
fully, haven't looked at this again

**Comment by marcusandre** [comment]
https://github.com/honza/vim-snippets – check while redoing vim things.

**Comment by yoshuawuyts** [comment]
yeah, I'm using that now! :D

**Comment by marcusandre** [comment]
Sorry, I took a few days off. Satisfied? Snippets would be really nice! 👍  
I might start from scratch if I get more time soon. Learned a lot and I'm quite motivated to clean up the _dotfiles_ mess. :)

**Comment by yoshuawuyts** [comment]
well, sorta satisfied - they're nowhere near as good as sublime still tho :(

**Comment by marcusandre** [comment]
That's so true. Makes me jealous sometimes. :(

**Comment by marcusandre** [comment]
SirVer/ultisnips + honza/vim-snippets work pretty well for Vim 8.
I'll switch to my own snippets more and more if I find time.
