### ISSUE TITLE
Add zsh-users/antigen

### ISSUE THREAD

**Issue by marcusandre** [marcusandre/dotfiles#12]
https://github.com/zsh-users/antigen

**Comment by marcusandre** [comment]
also search, try and add zsh best practices

**Comment by yoshuawuyts** [comment]
Oh yeah, antigen is good!

**Comment by marcusandre** [comment]
You're using it too? Ah, I see you handle your dotfiles well. :) I'm switching to zsh because of some performance issues on my working machine lately. zsh plays nicely with tmux, and the ecosystem is quite nice. I don't like this bloated oh-my-zsh thing, though. Antigen seems well-suited.

**Comment by marcusandre** [comment]
I'm happy. Done.
